plugins {
    id 'fabric-loom' version '1.10.5'
    id 'com.replaymod.preprocess'
    id 'maven-publish'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

sourceCompatibility = JavaVersion.VERSION_16
targetCompatibility = JavaVersion.VERSION_16

archivesBaseName = project.archives_base_name + '-' + project.minecraft_version
version = project.mod_version
group = project.maven_group

repositories {
    mavenCentral()
    maven {
        url = "https://maven.fabricmc.net/"
    }
    maven {
        url = "https://www.cursemaven.com"
    }
}

configurations {
    annotationProcessor.extendsFrom compileClasspath
    shadowInclude
}

dependencies {

    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "curse.maven:litematica-${project.litematica_minecraft_version}-308892:${project.litematica_fileid}"
    modImplementation "curse.maven:malilib-${project.litematica_minecraft_version}-303119:${project.malilib_fileid}"

    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    implementation "org.apache.logging.log4j:log4j-api:2.17.2"
    compileOnly "org.apache.logging.log4j:log4j-core:2.17.2"
    runtimeOnly "org.apache.logging.log4j:log4j-core:2.17.2"

    implementation "org.apache.poi:poi:5.2.5"
    shadowInclude "org.apache.poi:poi:5.2.5"
    implementation ("org.apache.poi:poi-ooxml:5.2.5") {
        exclude group: "org.apache.poi", module: "ooxml-schemas"
    }
    shadowInclude ("org.apache.poi:poi-ooxml:5.2.5") {
        exclude group: "org.apache.poi", module: "ooxml-schemas"
    }
    implementation "org.apache.poi:poi-ooxml-lite:5.2.5"
    shadowInclude "org.apache.poi:poi-ooxml-lite:5.2.5"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {

    it.options.encoding = "UTF-8"

    def targetVersion = 16
    if (JavaVersion.current().isJava9Compatible()) {
        it.options.release = targetVersion
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.named("shadowJar") {
    archiveClassifier.set("")
    destinationDirectory = layout.buildDirectory.dir("tmp-shadow")
    configurations = [project.configurations.shadowInclude]
}

tasks.named("remapJar") {
    dependsOn tasks.named("shadowJar")
    inputFile.set(tasks.named("shadowJar").get().archiveFile)
    archiveClassifier.set("")
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {

            artifact(remapJar) {
                builtBy remapJar
            }
        }
    }

    repositories {

    }
}
