pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Jitpack'
            url = 'https://maven.fallenbreath.me/jitpack'
        }
        maven {
            name = 'JitpackOrigin'
            url = 'https://jitpack.io'
        }
        mavenCentral()
        gradlePluginPortal()
    }
    resolutionStrategy {
        eachPlugin {
            switch (requested.id.id) {
                case 'com.replaymod.preprocess': {
                    useModule "com.github.ReplayMod:preprocessor:$requested.version"
                    break
                }
                case 'net.fabricmc.fabric-loom':
                case 'net.fabricmc.fabric-loom-remap': {
                    useModule "net.fabricmc:fabric-loom:${requested.version}"
                    break
                }
            }
        }
    }
}

file('versions').eachDir { dir ->
    final String version = ":$dir.name"
    include version
    final ProjectDescriptor projectDescriptor = project version
    projectDescriptor.projectDir = dir
    projectDescriptor.buildFileName = '../../common.gradle'
}
